# Welcome to Nubia Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.4

# Site settings
title:              Mi Electric Scooters Xiaomi, Ninebot | Red Dot "Best of the Best" Award, as well as the iF Design Award 2017.
logo:               # Logo image URL
description:        Light weight and foldable electric scooters, Best royal Xiaomi scooters from the UK's only specialist Electric Scooter store, Royal Scooters.
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://royalscooters.co.uk/' # The base hostname & protocol for your site
twitter:            https://twitter.com/royalscooters
facebook:           https://www.facebook.com/royalscooters
instagram:          https://www.instagram.com/royalscooters

markdown:  kramdown
permalink: pretty
paginate:  11
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

collections:
 - products

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  SlavaVolokha:
    name:     Slava Volokha
    bio:      Your advisor in Electic Scooters world. I love save the nature & save time using electric scooters instead of tube or public transport.
    gravatar: https://s.gravatar.com/avatar/b1b87f79c97bcc851dc8a2c48207e528?s=150
    email:    me@royalscooters.co.uk
    website:  http://royalscooters.co.uk
    facebook:   https://facebook.com/slavavolokha